### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by GitEbachS** [GitEbachS/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#13]
https://dbdiagram.io/d/64c54d0502bd1c4a5ee89dc7

**Comment by ajawashington** [comment]
@GitEbachS Since you are not saving your user object into your database (it is being saved in OAuth instead) you do not need a user table on your ERD and no need to specify where the connection is. 

Also, the FirebaseKey is the entry primary key so it will not be connected to the user table. ❇️
