### ISSUE TITLE
Create entry page

### ISSUE THREAD

**Issue by GitEbachS** [GitEbachS/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#9]
When the user clicks on the create entry button on the vocab page, they should be directed to the create entry form. They can enter the following values:

- [ ] Title (placeholder: enter a word or phrase)
- [ ] - [ ] Definition (placeholder: enter a definition)
- [ ] - [ ] Language/Tech (placeholder: enter a language)

When the user clicks on the "Submit" button, the vocabulary object should be captured, and added to the array of vocabulary items.

**Comment by ajawashington** [comment]
@GitEbachS I would go deeper and think about what else is needed to achieve. Such as the API call, the data captured not in the input, and what should happen on the dom after the entry has been added to the database. ❇️
